### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by jose-django** [zorzalo3/zorza#26] opened 2019-12-11 17:17 UTC
page not found
Request Method: | GET
-- | --
http://127.0.0.1:8000/timetable/class/1/
timetable.views.show_class_timetable
No Class matches the given query.

**Comment by DietPawel** [comment] 2019-12-11 18:06
Thank You for your interest in this project!
I think this error came up, because You didn't loaded any timetable.
Please refer to [zorza_scripts repo](https://github.com/zorzalo3/zorza_scripts) to load timetable from xml file, or load demo db using fixture:
``
./manage.py flush #this flushes the db!!!`
./manage.py loaddata fixtures/demo.json
```

I'll close this issue, because it's not reproducible as can be seen [on production](https://zorza.lo3.wroc.pl/timetable/class/1/)

**Closed** 2019-12-11 18:06 UTC
